pluginManagement {
	repositories {
		gradlePluginPortal()
		maven {
			name = "NeoForged"
			url = uri("https://maven.neoforged.net/releases")
			content {
				includeGroup("net.neoforged")
			}
		}
		mavenCentral()
	}

	plugins {
		id 'net.neoforged.moddev' version '2.0.144'
		id 'net.neoforged.moddev.repositories' version '2.0.144'
		id 'org.moddedmc.wiki.toolkit' version '0.3.2'
	}
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
	id 'net.neoforged.moddev.repositories'
}

dependencyResolutionManagement {
	repositoriesMode = RepositoriesMode.PREFER_SETTINGS
//	rulesMode = RulesMode.FAIL_ON_PROJECT_RULES

	repositories {
		maven {
			name = "Alex's Caves (local checkout)"
			url = uri("file:///D:/Programs/GitHub/AlexsCaves-1.21.1/mcmodsrepo")
			content {
				includeGroup("com.github.alexthe668")
			}
		}
		exclusiveContent {
			forRepositories(
					mavenLocal(),
					maven {
						name = "RyanHCode Maven"
						url = uri("https://maven.ryanhcode.dev/releases")
					}
			)
			filter {
				includeGroup("dev.ryanhcode.sable")
				includeGroup("dev.ryanhcode.sable-companion")
			}
		}
		maven {
			name = "NeoForged"
			url = uri("https://maven.neoforged.net/releases")
			content {
				includeGroup("net.neoforged")
			}
		}
		maven {
			url "https://maven.sinytra.org"
		}
		maven {
			name = "ParchmentMC"
			url = uri("https://maven.parchmentmc.org")
			content {
				includeGroup("org.parchmentmc.data")
			}
		}
		mavenCentral()

		maven {
			name = "Curse Maven"
			url = uri("https://cursemaven.com")
			content {
				includeGroup("curse.maven")
			}
		}

		maven {
			name = "Modrinth Maven"
			url = uri("https://api.modrinth.com/maven")
			content {
				includeGroup("maven.modrinth")
			}
		}

		maven { url = "https://dvs1.progwml6.com/files/maven/" }  // JEI
		maven { url = "https://modmaven.k-4u.nl" }  // JEI backup
		maven {
			name = 'Geckolib'
			url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
			content {
				includeGroupByRegex("software\\.bernie.*")
				includeGroup("com.eliotlash.mclib")
			}
		}
		maven { url = 'https://maven.blamejared.com' }
		maven {
			url "https://dl.cloudsmith.io/public/klikli-dev/mods/maven/"
			content {
				includeGroup "com.klikli_dev"
			}
		}
		maven {
			name = 'tterrag maven'
			url = 'https://maven.tterrag.com/'
		}
		maven {
			name = 'KubeJS'
			url "https://maven.latvian.dev/releases"
			content {
				includeGroup "dev.latvian.mods"
				includeGroup "dev.latvian.apps"
			}
		}
		maven {
			url = "https://jitpack.io"
			content {
				includeGroup "com.github.rtyley"
			}
		}
		maven {
			name = "Shedaniel's maven"
			url = "https://maven.architectury.dev"
			content {
				includeGroup "dev.architectury"
			}
		}
	}
}
