@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.elenterius.spatialdb;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;