@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.elenterius.spatialdb.mvstore;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;