@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.elenterius.spatialdb.geometry;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;