# This workflow will build the Mod with Gradle and cache/restore any dependencies to improve the workflow execution time
# Note: cache writing only happens on the default branch but child branches do have read access to the default branch

name: Build Production Release

on:
  workflow_dispatch:
#  push:
#    branches:
#      - '**/prod'

permissions:
  contents: write

jobs:
  check_if_should_build:
    name: Check if a build should be triggered
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.changelog.outputs.skipped }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5.0.0

      - name: Get Minecraft Version
        id: gradle_properties
        uses: christian-draeger/read-properties@1.1.0
        with:
          path: './gradle.properties'
          properties: 'minecraft_version'

      - name: Generate Conventional Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6.1.0
        with:
          preset: 'conventionalcommits'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: './gradle.properties'
          version-path: 'mod_semantic_version'
          tag-prefix: '${{ steps.gradle_properties.outputs.minecraft_version }}-v2.'
          release-count: 1 # limit changelog to the current snapshot
          skip-commit: true # do not commit version bump
          skip-tag: true # do not commit version tag


  setup_oxipng:
    name: Install Oxipng
    needs: [ check_if_should_build ]
    if: needs.check_if_should_build.outputs.skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Cargo Install Oxipng
        uses: baptiste0928/cargo-install@v3.3.1 #provides cache-efficient Rust crates installation
        with:
          crate: oxipng
        env:
          CARGO_TERM_COLOR: always


  build_test:
    name: Gradle Build Test
    needs: [ check_if_should_build ]
    if: needs.check_if_should_build.outputs.skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-java@v5.0.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup/Cache Gradle & Validate Wrapper
        uses: gradle/actions/setup-gradle@v4.4.2

      - name: Test Asset Generation
        run: ./gradlew runData

      - name: Test Build
        run: ./gradlew build


  build_release:
    name: Build Release
    needs: [ build_test, setup_oxipng ]
    if: needs.changelog.outputs.skip_build == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Install Oxipng
        uses: baptiste0928/cargo-install@v3.3.2
        with:
          crate: oxipng
        env:
          CARGO_TERM_COLOR: always

      - name: Checkout Repository
        uses: actions/checkout@v5.0.0

      - name: Get Minecraft Version
        id: gradle_properties
        uses: christian-draeger/read-properties@1.1.0
        with:
          path: './gradle.properties'
          properties: 'minecraft_version'

      - name: Generate Conventional Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6.1.0
        with:
          preset: 'conventionalcommits'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: './gradle.properties'
          version-path: 'mod_semantic_version'
          git-message: 'chore(release): {version}'
          tag-prefix: '${{ steps.gradle_properties.outputs.minecraft_version }}-v2.'
          create-summary: true

      # ----------------------------------------------------------------------------------------------------------------

      - name: Setup JDK 17
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.4.2

      - name: Generate Assets
        run: ./gradlew runData

      - name: Optimize PNG Assets
        run: |
          oxipng -o 3 -i 0 --strip safe -r ./src/*/resources/*.png
          oxipng -o 3 -i 0 --strip safe -r ./src/*/resources/assets/*/textures
        env:
          CARGO_TERM_COLOR: always

      - name: Build Artifact
        run: ./gradlew build

      # ----------------------------------------------------------------------------------------------------------------

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ needs.changelog.outputs.tag }}
          body: ${{ needs.changelog.outputs.clean_changelog }}
          files: build/libs/*.jar
          make_latest: true

      # ----------------------------------------------------------------------------------------------------------------

      - name: Notify Discord Server
        uses: sarisia/actions-status-discord@v1.15.3
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          nodetail: true
          color: 0x088c7d
          username: "Maykr Bot"
          content: "<@&1098316788116246550>"
          title: ":package: New Biomancy Release Candidate Available!"
          description: |
            ## Version: `${{ steps.changelog.outputs.tag }}`
            ## [View changelog and download on GitHub](${{ steps.create_release.outputs.url }})
            File SHA-256: `${{ steps.artifact-upload.outputs.artifact-digest }}`
