name: Poke Discord

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message'
        required: true
        default: 'foobar'

jobs:
  notify_discord:
    name: Notify Discord Server
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1.15.3
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          nodetail: true
          content: "<@&1155558469617852497>"
          title: "Hello World!"
          description: |
            ${{ github.event.inputs.message }}
            Click [here](https://youtu.be/dQw4w9WgXcQ) to download!
          color: 0xffd700
          username: "Maykrs Herald"
